### PR TITLE
Added partial IPV6 support

### PR DESCRIPTION
**Pull request by jmdaweb**
The following changes have been made:

* The server has an additional socket to listen on IPV6.
* socket_utils.address_to_hostport: if hostname contains : and starts with [, this is an IPV6 address. Otherwise it is processed as IPV4, so hostnames still don't resolve to IPV6 addresses. socket.getaddrinfo() should be called somewhere in the code, but I don't know exactly where. Also, as Christopher told me, regular expressions can help.
* transport.py: TCPTransport creates an IPV6 socket if it receives an IPV6 address.
* Connection_info generates nvdaremote:// links for IPV6 addresses.
* Changed __init__.py and session.py to work with these modifications and fix bugs.

To connect to an IPV6 address, use the following format: [ip]:port, or [ip] only for the default port. IPV6 address must be between brackets.
My unofficial server has IPV6 support. If nvdaremote.com isn't ready yet, you can use the following information to perform tests:

* hostname: acorta.me
* IPV4 address: 104.238.135.0
* IPV6 address: 2001:19f0:5:1bbd:5400:ff:fe70:3771

Regards.

### CODE REVIEW

**Comment by leonardder** [comment]
What does this do on legacy systems where ipv6 is not supported?

**Comment by jmdaweb** [comment]
Since Windows xp sp3 is the oldest version supported by recent NVDA versions, it won't be any problems. Windows XP supports IPV6. I have called socket.has_ipv6 from the Python console on an xp virtual machine and it returns True.

**Comment by leonardder** [comment]
It is still possible to force disable IPV 6, see [this](https://support.microsoft.com/en-us/help/929852/how-to-disable-ipv6-or-its-components-in-windows) article. Not trying to be silly here, but I think we really need to be sure that it never breaks if exception handling isn't used for this code.

Also note for your remote server that for Linux, it is quite easy to disable IPV6 at the kernel level. I did this for some systems where IPV6 wasn't available, and it was the easiest way to get rid of everything IPV6 related.

**Comment by jmdaweb** [comment]
My server handles that situation. Only server.py file should be modified for this, I’ll send the commit soon.
Regards.

**Pull request closed without merging**
