### PR TITLE
Finnish translation

### PR DESCRIPTION
**Pull request by jkinnunen**
Finnish translation for the NVDA Remote add-on

### CODE REVIEW

**Comment by jkinnunen** [comment]
Can you please merge this?

**Comment by tspivey** [comment]
It's missing the readme.

**Comment by jkinnunen** [comment]
Can this be merged now?

**Comment by jkinnunen** [comment]
Can you please merge this?

**Comment by pzajda** [comment]
Hi,

Last time I made a pull request, I asked why it was not merged and it was because it is better to have a single commit.
You can solve this by [Squashing](http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit) this pull request into a single commit.
Hop this helps.

**Comment by jkinnunen** [comment]
I don't know how to squash these commits, as I used the --amend option when I committed the readme file, and now the rebase command shows only one commit. Please note that since I'm not a developer, am not familiar with git, and the more I read and think about it, the more I get confused.

**Pull request closed without merging**
