### PR TITLE
Use NVDA configuration instead of remote.ini

### PR DESCRIPTION
**Pull request by jmdaweb**
Now the addon stores its settings using the NVDA configuration manager, so diferent profiles can have diferent configurations. The following changes have been made:

* configuration.py: converted the configspec into a dictionary, which is stored in config.conf.spec['remote']. The module variable _config references config.conf['remote'].
* configuration.py: removed unused imports and calls. We don't need StringIO, os.path and configobj because we use NVDA config module.
* configuration.py, dialogs.py and session.py: removed calls to conf.write(). NVDA will save the addon settings.

### CODE REVIEW

**Comment by tspivey** [comment]
Why would we want this?

I don't want my NVDA Remote configuration being affected by my current 
configuration profile. It's global to NVDA, not the application I'm running.

Brief testing shows that config profiles still don't affect things, 
because configuration.get_config relies on a global which is only 
updated if it's not already set.

The user experience wouldn't be very nice if they did. Everything I see 
in remote.ini right now, including servers I last connected to and auto 
connect, is global to NVDA, not a specific application.

**Comment by jmdaweb** [comment]
I have made this because the code is clearer, more eficient, and follow the NVDA addon development guidelines. It doesn’t fix any critical issue, it’s optional. I have developed some addons recently and I discovered these things.
Regards.

**Comment by leonardder** [comment]
I strongly agree with Tyler here. Using NVDA's config system is also 
undesirable for secure desktop configurations.

**Comment by jmdaweb** [comment]
Ok, I understand you, and you have reason. However, with this pull request the settings are still global, but they are saved using NVDA config system. The results are exactly the same, with less code and less files. I'll leave this pull request opened, so you can merge if your opinion changes.
Regards.

**Pull request closed without merging**
