### PR TITLE
Implement sounds for pushing and receiving the clipboard.

### PR DESCRIPTION
**Pull request by TheQuinbox**

### CODE REVIEW

**Comment by lbk2907** [comment]
I like this feature.
Nice contribution.
Are the pushing and receiving clipboard use the same sound?
If yes, maybe the audio file name can be change to clipboard.wav.

**Comment by lbk2907** [comment]
If both are them are using the different sound, maybe the file name can be
clipboard_pushed.wav and clipboard_received.wav.
I haven't check the code yet since I'm reply to this pull request use my
phone.
😊

**Comment by TheQuinbox** [comment]
Nope, they're two different sounds. I reversed the intro to the (before unused), push_clipboard.wav sound, and made it the receive_clipboard sound.

**Comment by lbk2907** [comment]
Nice.
Thanks.

**Pull request merged**
