### PR TITLE
Use 2024.1 API for secure desktop changes

### PR DESCRIPTION
**Pull request by seanbudd**
https://github.com/nvaccess/nvda/pull/14488 proposes a change of API, which will break how NVDA remote interacts with a secure desktop. This PR has been created to support this new API. NVDARemote compatibility with other API breaking changes have not been tested, as this is the main change we are concerned with integrating into NVDARemote.
There may be other API changes proposed for 2023.1 that affect NVDARemote.

A smoke test of NVDA remote is required for this including the following:
- [x] a https://github.com/nvaccess/nvda/pull/14488 instance (with patched add-on) controlling/controlled by an 2022.4 instance (with released add-on). 
- [x] a https://github.com/nvaccess/nvda/pull/14488 instance (with patched add-on) controlling/controlled by a https://github.com/nvaccess/nvda/pull/14488 instance (with patched add-on). 
Testing the following functionality:
  - going through the lock/login workflow. ensuring the sign-in screen works as expected
  - testing the UAC dialog
      
 A packaged copy of the patched addon can be downloaded here to test with: 
[remote-2.5.zip](https://github.com/NVDARemote/NVDARemote/files/10356662/remote-2.5.zip)
A try build of the proposed NVDA changes can be downloaded here to test with: https://ci.appveyor.com/api/buildjobs/gq8kprbkssea2lbp/artifacts/output%2Fnvda_snapshot_try-remove-SecureDesktopNVDAObject-27444%2C15dbc382.exe

### CODE REVIEW

**Comment by ctoth** [comment]
Thanks for your work on this! I'll review and test it and attempt to get it merged this weekend!

**Comment by amirmahdifard** [comment]
@ctoth do you know a fact that it is now so long after you said this week end? i need remote addon  for my job to connect to the servers of my job but nvda remote will be lost in 2023.1, and nvda 2023 is almoste out, i also suggested something for this project and you didn't care!

**Comment by seanbudd** [comment]
Marking as draft as this PR has been postponed until 2024.1

**Comment by seanbudd** [comment]
Note the PR as it currently stands is incompatible with 2023.X, further modifications are needed if NVDARemote wishes to release an add-on version which supports both 2023.X and 2024.X

**Comment by seanbudd** [comment]
Marking as ready for review as https://github.com/nvaccess/nvda/pull/14488 has been merged

**Comment by codeofdusk** [comment]
Given the imminent release of NVDA 2024.1, are there any updates on the merging of this PR?

**Comment by ctoth** [comment]
@codeofdusk, thanks for the reminder about the NVDA 2024.1 release. We're juggling quite a few priorities, and not everyone has the bandwidth to track specific release schedules closely. I'll check the status of this PR and provide an update. We value your diligence and understanding as we balance various project demands.

**Comment by seanbudd** [comment]
Closing in favour of https://github.com/NVDARemote/NVDARemote/pull/330

**Pull request closed without merging**
