### PR TITLE
Added connect and disconnect gestures

### PR DESCRIPTION
**Pull request by Oliver2213**
These gestures are changeable from NVDA's input gestures screen and have preset values that I'm reasonably sure don't conflict with other add-ons.

### CODE REVIEW

**Comment by ctoth** [comment]
I am reluctant to set these by default as it is already only 3 
keystrokes to accomplish either, and we can't know the space of possible 
add-ons in the future.
What do you think, @tspivey?

On 8/1/2015 10:19 PM, Oliver2213 wrote:
>
> These gestures are changeable from NVDA's input gestures screen and 
> have preset values that I'm reasonably sure don't conflict with other 
> add-ons.
>
> ------------------------------------------------------------------------
>
>
>         You can view, comment on, or merge this pull request online at:
>
> https://github.com/NVDARemote/NVDARemote/pull/43
>
>
>         Commit Summary
>
>   * Added a gesture to open the connect dialog, fixed disconnect gesture
>
>
>         File Changes
>
>   * *M* addon/globalPlugins/remoteClient/__init__.py
>     <https://github.com/NVDARemote/NVDARemote/pull/43/files#diff-0> (26)
>
>
>         Patch Links:
>
>   * https://github.com/NVDARemote/NVDARemote/pull/43.patch
>   * https://github.com/NVDARemote/NVDARemote/pull/43.diff
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/NVDARemote/NVDARemote/pull/43>.
>


-- 
		-Q

	Accessible Software for the Blind
http://GetAccessibleApps.com

**Comment by tspivey** [comment]
I also agree with this. Just like mute, I think we should have them
there, but unset by default.

**Comment by Oliver2213** [comment]
Understandable, I'll remove the default bindings, then.

**Comment by leonardder** [comment]
@Oliver2213: Could you resolve the conflicts with master?

**Comment by Oliver2213** [comment]
Alright, working on it.

**Comment by bdorer** [comment]
Is this wanted, if not I think the request should be closed as it is likely outdated.t

**Comment by TheQuinbox** [comment]
This is definitely out-dated. The default NVDA Remote disconnect command is now Alt NVDA page down, for example.

**Pull request closed without merging**
